//! This module defines structs that are shared by all sub protocols.

use ark_ff::PrimeField;
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};

use crate::arithmetic::{mat_poly::mle::MLE, virt_poly::hp_interface::HPVirtualPolynomial};
/// An IOP proof is a collections of
/// - messages from prover to verifier at each round through the interactive
///   protocol.
/// - a point that is generated by the transcript for evaluation
#[derive(Clone, Debug, Default, PartialEq, Eq, CanonicalSerialize, CanonicalDeserialize)]
pub struct SumcheckProof<F: PrimeField> {
    pub point: Vec<F>,
    pub proofs: Vec<SumcheckProverMessage<F>>,
}

/// A message from the prover to the verifier at a given round
/// is a list of evaluations.
#[derive(Clone, Debug, Default, PartialEq, Eq, CanonicalSerialize, CanonicalDeserialize)]
pub struct SumcheckProverMessage<F: PrimeField> {
    pub(crate) evaluations: Vec<F>,
}

/// Prover State of a PolyIOP.
pub struct SumcheckProverState<F: PrimeField> {
    /// sampled randomness given by the verifier
    pub challenges: Vec<F>,
    /// the current round number
    pub(crate) round: usize,
    /// pointer to the virtual polynomial
    pub(crate) poly: HPVirtualPolynomial<F>,
    /// points with precomputed barycentric weights for extrapolating smaller
    /// degree uni-polys to `max_degree + 1` evaluations.
    pub(crate) extrapolation_aux: Vec<(Vec<F>, Vec<F>)>,
    /// Owned working set of Field-storage MLEs. Populated on the first call
    /// to `prove_round_and_update_state` by lifting the Arc-shared MLEs out
    /// of `poly.flattened_ml_extensions` into owned `Vec<F>` buffers (via
    /// `Arc::try_unwrap` when refcount == 1, else `to_field_owned`). Every
    /// subsequent round folds these buffers in place via
    /// [`MLE::fix_one_variable_in_place`]. This is what keeps sumcheck's
    /// round-loop allocation traffic to a single lift plus in-place
    /// truncations across all rounds — instead of a fresh clone-plus-fix
    /// pair per round as the previous scheme did.
    pub(crate) flattened_mles: Vec<MLE<F>>,
    /// True after the first call to `prove_round_and_update_state` has
    /// moved evaluations into `flattened_mles` and cleared
    /// `poly.flattened_ml_extensions`.
    pub(crate) mles_initialized: bool,
}

/// Prover State of a PolyIOP
pub struct SumcheckVerifierState<F: PrimeField> {
    pub(crate) round: usize,
    pub(crate) num_vars: usize,
    pub(crate) max_degree: usize,
    pub(crate) finished: bool,
    /// a list storing the univariate polynomial in evaluation form sent by the
    /// prover at each round
    pub(crate) polynomials_received: Vec<Vec<F>>,
    /// a list storing the randomness sampled by the verifier at each round
    pub(crate) challenges: Vec<F>,
}
